services:
  proxy:
    image: traefik:latest
    container_name: traefik
    depends_on:
      - authelia
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@somtube.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.websecure.http.tls.domains[0].main=somtube.com"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.somtube.com"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik/letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.somtube.com`)"
      - "traefik.http.routers.api.entryPoints=websecure"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=authelia@docker"

  authelia_redis:
    image: redis:latest
    container_name: authelia_redis
    restart: unless-stopped

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    depends_on:
      - authelia_redis
    volumes:
      - ./data/authelia:/config
    restart: unless-stopped
    expose:
      - 9091
    environment:
      TZ: "${TIME_ZONE}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`authelia.somtube.com`)"
      - "traefik.http.routers.authelia.entryPoints=websecure"
      - "traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/authz/forward-auth"
      - "traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email,Remote-Name"

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - TZ="${TIME_ZONE}"
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/jellyfin/config:/config
      - ./data/media/movies:/movies
      - ./data/media/tv:/tv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`somtube.com`)"
      - "traefik.http.routers.jellyfin.entryPoints=websecure"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - TZ="${TIME_ZONE}"
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/sonarr/config:/config
      - ./data/media/tv:/tv
      - ./data/media/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.somtube.com`)"
      - "traefik.http.routers.sonarr.entryPoints=websecure"
      - "traefik.http.routers.sonarr.middlewares=authelia@docker"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - TZ="${TIME_ZONE}"
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/radarr/config:/config
      - ./data/media/movies:/movies
      - ./data/media/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.somtube.com`)"
      - "traefik.http.routers.radarr.entryPoints=websecure"
      - "traefik.http.routers.radarr.middlewares=authelia@docker"

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - TZ="${TIME_ZONE}"
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/bazarr/config:/config
      - ./data/media/movies:/movies
      - ./data/media/tv:/tv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.somtube.com`)"
      - "traefik.http.routers.bazarr.entryPoints=websecure"
      - "traefik.http.routers.bazarr.middlewares=authelia@docker"

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - TZ="${TIME_ZONE}"
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/jellyseerr/config:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(`requests.somtube.com`)"
      - "traefik.http.routers.jellyseerr.entryPoints=websecure"
      - "traefik.http.routers.jellyseerr.middlewares=authelia@docker"

  jfa-go:
    image: hrfee/jfa-go:latest
    container_name: jfa-go
    restart: unless-stopped
    environment:
      - TZ="${TIME_ZONE}"
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/jfa-go:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jfa.rule=Host(`accounts.somtube.com`)"
      - "traefik.http.routers.jfa.entryPoints=websecure"
      - "traefik.http.routers.jfa.middlewares=authelia@docker"

  homer:
    image: b4bz/homer:latest
    container_name: homer
    restart: unless-stopped
    environment:
      - TZ="${TIME_ZONE}"
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/homer:/www/assets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.rule=Host(`dashboard.somtube.com`)"
      - "traefik.http.routers.homer.entryPoints=websecure"
      - "traefik.http.routers.homer.middlewares=authelia@docker"

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    environment:
      - TZ="${TIME_ZONE}"
      - PUID=1000
      - PGID=1000
      - FB_BASEURL=/
    volumes:
      - ./data/media:/srv
      - ./data/filebrowser/config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.somtube.com`)"
      - "traefik.http.routers.filebrowser.entryPoints=websecure"
      - "traefik.http.routers.filebrowser.middlewares=authelia@docker"

networks:
  default:
    driver: bridge
